name: Fuzzing

on:
  push:
    branches: [ main, fuzz ]
  pull_request:
    branches: [ main, fuzz ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fuzz-ubuntu:
    name: Fuzz on Ubuntu
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-20.04, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: 'recursive'

    - name: Linux Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libevent-dev

    - name: Install Clang
      run: |
        sudo apt-get install -y clang

    - name: Update Submodule
      run: |
        git submodule update --init --recursive

    - name: Build BoringSSL
      run: |
        git clone https://github.com/google/boringssl.git ./third_party/boringssl
        cd ./third_party/boringssl
        mkdir -p build
        cd build
        cmake -DBUILD_SHARED_LIBS=0 -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" ..
        make ssl crypto

    - name: Build XQUIC with Fuzzing
      run: |
        SSL_TYPE_STR="boringssl"
        SSL_PATH_STR="${PWD}/third_party/boringssl"
        mkdir -p build
        cd build
        cmake -DENABLE_FUZZING=ON -DSSL_TYPE=${SSL_TYPE_STR} -DSSL_PATH=${SSL_PATH_STR} ..
        make fuzz

    - name: Run Fuzzing Tests
      run: |
        cd build
        make run_packet_fuzzer
        make run_frame_fuzzer
        make run_stream_fuzzer
        make run_state_fuzzer
        make run_h3_fuzzer

  fuzz-macos:
    name: Fuzz on macOS
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [macos-11, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: 'recursive'

    - name: Update Submodule
      run: |
        git submodule update --init --recursive

    - name: Build BoringSSL
      run: |
        git clone https://github.com/google/boringssl.git ./third_party/boringssl
        cd ./third_party/boringssl
        mkdir -p build
        cd build
        cmake -DBUILD_SHARED_LIBS=0 -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" ..
        make ssl crypto

    - name: Build XQUIC with Fuzzing
      run: |
        SSL_TYPE_STR="boringssl"
        SSL_PATH_STR="${PWD}/third_party/boringssl"
        mkdir -p build
        cd build
        cmake -DPLATFORM=mac -DENABLE_FUZZING=ON -DSSL_TYPE=${SSL_TYPE_STR} -DSSL_PATH=${SSL_PATH_STR} ..
        make fuzz

    - name: Run Fuzzing Tests
      run: |
        cd build
        make run_packet_fuzzer
        make run_frame_fuzzer
        make run_stream_fuzzer
        make run_state_fuzzer
        make run_h3_fuzzer